# Generated by Django 2.2.5 on 2019-10-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsadayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipoAtividade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jsadayapp.TipoAtividade'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='nivel',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='humor',
            name='sensacoes',
            field=models.ManyToManyField(default=None, to='jsadayapp.Sensacao'),
        ),
    ]
