# Generated by Django 2.2.5 on 2019-10-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsadayapp', '0002_auto_20191022_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='nome',
            field=models.CharField(max_length=12),
        ),
    ]
