# Generated by Django 2.2.5 on 2019-10-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsadayapp', '0003_auto_20191022_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizacao',
            name='humor',
        ),
        migrations.AddField(
            model_name='humor',
            name='realizacoes',
            field=models.ManyToManyField(default=None, to='jsadayapp.Realizacao'),
        ),
    ]
