# Generated by Django 2.2.5 on 2019-10-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsadayapp', '0004_auto_20191022_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humor',
            name='sensacoes',
            field=models.ManyToManyField(default=None, null=True, to='jsadayapp.Sensacao'),
        ),
    ]
