# Generated by Django 2.2.6 on 2019-10-23 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12)),
                ('codigo', models.CharField(max_length=1)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nivel', models.CharField(default=None, max_length=1)),
                ('descricao', models.TextField(default='', null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Realizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_realizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('atividade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jsadayapp.Atividade')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Humor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nivel', models.CharField(default=None, max_length=1)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True, default='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('realizacoes', models.ManyToManyField(default=None, to='jsadayapp.Realizacao')),
                ('sensacoes', models.ManyToManyField(default=None, to='jsadayapp.Sensacao')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipoAtividade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jsadayapp.TipoAtividade'),
        ),
    ]
