# Generated by Django 2.2.6 on 2019-10-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsadayapp', '0004_auto_20191023_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humor',
            name='nivel',
            field=models.CharField(choices=[('-2', 'Muito negativo'), ('-1', 'Negativo'), ('0', 'Neutro'), ('1', 'Positivo'), ('2', 'Muito positivo')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='humor',
            name='sensacoes',
            field=models.ManyToManyField(related_name='humores', to='jsadayapp.Sensacao'),
        ),
        migrations.AlterField(
            model_name='sensacao',
            name='nivel',
            field=models.CharField(choices=[('-2', 'Muito negativo'), ('-1', 'Negativo'), ('0', 'Neutro'), ('1', 'Positivo'), ('2', 'Muito positivo')], default=0, max_length=1),
        ),
    ]
