# Generated by Django 2.2.6 on 2019-10-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsadayapp', '0005_auto_20191024_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacao',
            name='atividade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='realizacao_atividade', to='jsadayapp.Atividade'),
        ),
    ]
