# Generated by Django 2.2.6 on 2019-11-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsadayapp', '0006_auto_20191030_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humor',
            name='nivel',
            field=models.CharField(choices=[('0', 'Muito negativo'), ('1', 'Negativo'), ('2', 'Neutro'), ('3', 'Positivo'), ('4', 'Muito positivo')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='sensacao',
            name='nivel',
            field=models.CharField(choices=[('0', 'Muito negativo'), ('1', 'Negativo'), ('2', 'Neutro'), ('3', 'Positivo'), ('4', 'Muito positivo')], default=0, max_length=1),
        ),
    ]
