# Generated by Django 2.2.6 on 2019-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsadayapp', '0007_auto_20191104_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humor',
            name='nome',
        ),
        migrations.AlterField(
            model_name='humor',
            name='realizacoes',
            field=models.ManyToManyField(related_name='humores_realizacoes', to='jsadayapp.Realizacao'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='sensacoes',
            field=models.ManyToManyField(related_name='humores_sensacoes', to='jsadayapp.Sensacao'),
        ),
    ]
